### ISSUE TITLE
comments about chapt#1

### ISSUE THREAD

**Issue by pvilledieu** [ScPoEcon/ScPoEconometrics-Slides#1]
add : 

- slide with downloading links and instruction for R and RStudio (to avoid looking back at the book) 
- slide with the complete wrap up of the course materials 

update : 

- about the questions in slide 3 : keep multiple questions to give illustrations but prepare a synthetic answer for one in particular 
- package presentation (slide 27) : give an example, either coming back to showcase package or with a new one

**Comment by floswald** [comment]
closing via #5a801a08bdea5518996b97e6494eb77d1da30c8e
