### ISSUE TITLE
ATN missing

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics-Slides#49]
@gustavekenedi there is an ATN missing on slide 9 of the new causal slides

**Comment by gustavekenedi** [comment]
ATN?

**Comment by floswald** [comment]
Sorry slide 19

![image](https://user-images.githubusercontent.com/1021558/109042850-f3c54900-76d0-11eb-977a-87df800faf7d.png)

**Comment by gustavekenedi** [comment]
😩 
Well spotted thanks! I'll make the adjustment asap

**Comment by gustavekenedi** [comment]
#50

**Comment by gustavekenedi** [comment]
Thanks @floswald !
