### ISSUE TITLE
countdown timer does not show locally

### ISSUE THREAD

**Issue by floswald** [ScPoEcon/ScPoEconometrics-Slides#80]
hey team @gustavekenedi and @mylenefeuillade 

I'm having trouble getting the slides to run locally - the countdown timer seems to be an issue.

locally on my browser it looks like this

<img width="1579" alt="Screenshot 2022-07-29 at 14 16 12" src="https://user-images.githubusercontent.com/1021558/181756474-2aa5ba8f-9a87-4bb4-98cd-f746cecad578.png">

ie something messes up how this is served. I tried around with using different css's (even the built-in defaults) but that did not help. does the timer only work when served from a proper server ?

**Comment by gustavekenedi** [comment]
Just checked and it's working both in my RStudio Viewer pane and Chrome on my end 🤔 

![Screenshot 2022-07-29 at 14 55 37](https://user-images.githubusercontent.com/15594877/181765063-d6edb522-ebbc-483c-ab55-36ad20fb02ee.png)

**Comment by floswald** [comment]
that's really strange. for me it works in neither (not rstudio, not firefox and not chrome). chrome says it's up to date. javascript is enabled.

**Comment by floswald** [comment]
for me in general the preview in the rstudio viewer does not pick up the correct css - so I always look at the browser and manually reload. I thought that has to do with how we set up the css files (they are not in the "correct" location (same dir as the Rmd but rather in a folder `../css` so that we can use the same css for all. but that it works for you is surprising. What's your OS?

**Comment by gustavekenedi** [comment]
Are you loading the `R` project? In the past this was why I was not getting the right CSS.
I'm on Mac (11.6.5).

**Comment by floswald** [comment]
not exactly sure what you mean - I'm in Rstudio, in the `ScPoEconometrics-Slides` project, and I click on *knit* while looking at the Rmd file. is that how you do it?

**Comment by gustavekenedi** [comment]
I just meant whether you had the `ScPoEconometrics-Slides` project loaded (screenshot below), which it seems you do.
![Screenshot 2022-07-29 at 15 13 29](https://user-images.githubusercontent.com/15594877/181768019-13486116-ee86-4c94-ab26-102957bd0d0f.png)

I just run: (https://bookdown.org/yihui/rmarkdown/xaringan-preview.html)
```
library(xaringan)
inf_mr()
```
This is probably equivalent to clicking _knit_, I don't know.

**Comment by floswald** [comment]
that approach doesn't work any better, no. too bad

<img width="1199" alt="Screenshot 2022-07-29 at 15 24 29" src="https://user-images.githubusercontent.com/1021558/181769888-33ac828f-310c-46bf-a561-8fa4b39db799.png">

**Comment by gustavekenedi** [comment]
Hmmm how strange... I'm assuming you've made no changes to the YAML?

**Comment by floswald** [comment]
no, just pulled from master. that css thing has always bothered me, so it's just gotten worse with the countdown function. I've tried to compare the raw html that's being served online with what my computer generates, they don't differ up to the fact that it hardcodes my css stylesheet locally, while online it's a relative path, like `../css` whereas on my computer its `/Users/florian.oswald` etc 
as i said, turning off custom css altogether does not even change this! annoying.

**Comment by mylenefeuillade** [comment]
It works for me, both locally on Chrome, and on RStudio; and I'm on Windows
11.
Just like Gustave the only time I've had issues with the css were when I
was not knitting from the ScPoEconometrics-Slides project.

Le ven. 29 juil. 2022 à 15:32, Florian Oswald ***@***.***> a
écrit :

**Comment by floswald** [comment]
ok well not sure i'll get to the bottom of this. the timer is very cool, so will probably fly one-eyed locally and hope it all fits on the rendered slide on the server. wish me luck! :-)

**Comment by gustavekenedi** [comment]
🤞 🍀 

PS: `countdown` is neat but one quite annoying issue (though not deal breaking) is that you can't stop it once it's started 😅

**Comment by floswald** [comment]
yes i'll see - i used a super simple timer app on my screen so far, so if this gets too difficult I'll remove the timer

**Comment by floswald** [comment]
update to R 4.2 solved the issue! new version even with plus/minus button

<img width="882" alt="Screenshot 2022-08-18 at 10 25 50" src="https://user-images.githubusercontent.com/1021558/185347746-9d11ed61-6079-4339-a6a8-20e95c7cc2e0.png">

on/off also works now. awesome widget!
