### ISSUE TITLE
Chapter 1 HTML link not uptodate

### ISSUE THREAD

**Issue by gustavekenedi** [ScPoEcon/ScPoEconometrics-Slides#9]
For some reason the link to the slides for Lecture 1 directs to the old version of the slides... This is especially curious since the chapter1.html file is up to date. Hmmm. Any idea as to why that is?

**Comment by floswald** [comment]
are you sure? it says 28th of january and it has the crossed fingers.

**Comment by gustavekenedi** [comment]
Ok now it's working. Don't know what happened. Thanks!
